[options]
http_port = 9999
admin_passwd = admin123
db_host = localhost
db_port = 5432
db_user = odoo19
db_password = root
db_name = UY_SCUTI1
list_db = False
addons_path = D:\odoo-19.0\odoo-19.0\addons, D:\UYScuti_ERP
logfile = D:\UYScuti_ERP\odoo.log
log_level = info
dev_mode = reload 
workers = 0
xmlrpc_interface = 0.0.0.0
netrpc_interface = 0.0.0.0
xmlrpc_port = 9999
netrpc_port = 9999
# python odoo-bin -c odoo.conf
# python D:\odoo-19.0\odoo-19.0\odoo-bin -c D:\UYScuti_ERP\odoo.conf